### ISSUE TITLE
Work checklist

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1277]
- [x] load zip lens of repos, fully assed instead of path hardcode
- [x] error message catch and splat
- [x] special `.metaversefile` handling (handled by presence of file.doc)
- [x] selected object delete
- [x] file rename twizzler
- [x] editor page: re-sort buttons to left files sidebar
- [x] local file upload support
- [x] intelligent main file detection
- [x] optimize github directory download
- [x] redesign template system
- [x] auto-load templates on selection
- [x] download zip support
- [x] physics-based objects select
- [x] transform gizmo
- [x] per-app physics tracking
- [x] vr support
- [x] reboot aws multiplayer server
- [x] loading cube
- [x] loading bar
- [x] loaded cube
- [x] new orbit drag camera system
- [x] scroll wheel camera
- [x] refactor capsule geometry to buffer geometry
- [x] click select object unification
  - [x] UI update driven from change events in the engine
  - [x] engine handles internal clicking
  - [x] UI click causes engine selection
- [x] move html-render repo to app ./html-render
- [x] move html-render repo back to split origins for performance 
- [x] tone down mesh shader to be less blue
- [x] world lens boxes sorted
- [ ] render details in object ui meshes
  - [ ] token-based
  - [ ] set defaults for URLS
- [ ] object ui mesh single selection
- [ ] box multi-selection
  - [ ] multi-drag
- [ ] click pointer lock in editor mode bug
- [ ] unify object focus + delete in engine
- [ ] move mirror popup out of the way
  - [ ] to new popup system entirely
- [ ] integrate card rips
- [ ] glsl shader support ported from next branch
- [ ] context menu
  - [ ] new...
  - [ ] select
  - [ ] possess
  - [ ] wear
  - [ ] add to loadout
  - [ ] delete
- [ ] context menu New... option splat
- [ ] media query smallerizer (?)
- [ ] clear world before connecting in multiplayer
- [ ] transform gizmo functionality
- [ ] persistent file storage
- [ ] mint nft buttons in objects list
- [ ] user bar: [login, spawn, loadout, inventory]
- [ ] infinite scroll:
  - [ ] home page
  - [ ] editor library
- [ ] add anime
