### ISSUE TITLE
Animation : Current Todo List 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1943]
# Animation TODO list
[main gdrive link](https://drive.google.com/drive/folders/1C4q2hhT-ihrQ_WHYZWKrMZmrnV-pLlEM)
i will update this list as progress is made and also if any extra requests are made i will integrate all of that here. All of the todo animations will need playtesting and then further tweaking. 

## Jumping
_needs code implemented so animations can be seen blended together in order to make final tweaks_

* [gdrive link](https://drive.google.com/drive/folders/1MO25xLdkGmz_t2fcJPeiWYB0IWrMZZLy?usp=sharing)
* stand_charge
* charge_jump
* fall_loop
* landing 

## Grabbing 
 _needs code implemented so animations can be seen blended together in order to make final tweaks_

* [gdrive link](https://drive.google.com/drive/folders/1BbOrhq70V2fJm10lwbUJnULviK-VU66s?usp=sharing)
* grab_up
* grab_right
* grab_left
* grab_forward
* grab_down

## Throwing
_needs code implemented so animations can be seen blended together in order to make final tweaks_

* [gdrive link](https://drive.google.com/drive/folders/1LhysJwNjUAQqLa-VouTckgzYh_dLXnYj?usp=sharing)
* throw_forward

## Scillia Sword
* side slash
* top down slash
* sword idle
* draw sword from back
* undraw sword from back
**extra credit**
* top down slash combo step (opposite direction)
* side slash combo step (opposite direction)
* flair sword in a cool way and place on back; inspiration can be animations of cloud's battle victory from ff7 or link from zelda; however, it should be quite fast so it doesn't interrupt the flow of gameplay; it should last at most a second

## Drake Guns
* draw gun
* undraw gun
* rifle idle 
* rifle shoot 

## Chest Open
* [gdrive link](https://drive.google.com/drive/folders/1VNLqVczhmN_Cw8cwwB50Kx934DywGuUA?usp=sharing)
* chest open 
* peer inside chest / grab something in chest
* close chest

**Comment by avaer** [comment]
- [ ] light Contrapposto idle pose
![adventure](https://user-images.githubusercontent.com/6926057/146952858-72d228ff-7500-4bd5-94bf-c71cf606a813.jpg)
it should have an idle noise cycle, but not perform any meaningful movement
- [ ] hurt 1: curling the body inwards (but don't bounce back from a hit)
- [ ] hurt 2: arching the body backwards
NOTE: time for hurt animations: 1s. don't bounce back from a hit, it should be more more like being electrocuted and cringing at the pain
- [ ] eating animation: bring food close to mouth and chomp down aggressively
- [ ] drinking animation: we have one but it sucks; it should be inspired by fortnite slurps.
NOTE: the time for eating and drinking animations should be about 3s. in both cases we should make it relatively cartoony; we will use cartoon teleport physics to eat and drink things, where mouth contact does not need to be made with the object, so it is preferable to keep the hands and head separated. we will animate the mouth in code.
- [ ] silk worm: getting smacked backwards animation, with head tilted back

**Comment by avaer** [comment]
- [ ] "throw pokeball" animation; no stepping, mostly top half of the body; returns to idle pose (1s)
- [ ] "discard item" (throw object from right hand gently in front) (1s)
- [ ] pick up item and hold above head using both hands; link inspired (1s)
- [ ] idle cycle for holding item above head
- [ ] throw object from above head using over head throw

**Comment by plankatron** [comment]
@avaer there is a throw_forward animation that should work for "throw pokeball" request

**Comment by plankatron** [comment]
new animations for silkworm , silk_pain_back and silk_attack !
https://drive.google.com/file/d/1QBDsoWVAZstr6HQ1riskQ3modyo_soyf/view?usp=sharing

**Comment by plankatron** [comment]
https://drive.google.com/drive/folders/15BYiuDteWUpJJTAmdA1QxkN6goFNh50m?usp=sharing  
dir for hurt drink and eat animations ,, pain 1 / 2 at draft for qa

**Comment by avaer** [comment]
- [ ] sword deflect projectile/block. from bottom right to top left, from the character's view. another way of thinking about it is swinging upwards and left. it must be fast to get top the blocking part, but it would could pause in the midpoint before returning to idle.
![image](https://user-images.githubusercontent.com/6926057/147489656-351911ae-3da4-46af-ae2f-dcf72f4b7e37.png)
- [ ] variation on the above for variety, with an uppercut up the middle instead.
![image](https://user-images.githubusercontent.com/6926057/147489869-904413f2-9b14-4e6f-a1a5-8edebcdb865c.png)

**Comment by plankatron** [comment]
cross_arm pain anim , from what i understood it was sort of like the anime defense stance
this is actually two animations , pain_cross_open , pain_cross_close , i just quickly put them on the nla timeline both are around 11 frames long, for context this anim is 60 frames long
https://drive.google.com/drive/folders/15BYiuDteWUpJJTAmdA1QxkN6goFNh50m?usp=sharing

https://user-images.githubusercontent.com/5592454/147961512-6359349a-5193-4a85-b2bd-046687d927b8.mp4

**Comment by plankatron** [comment]
eating animation
https://user-images.githubusercontent.com/5592454/147974308-a10073ba-5384-4af3-8aa1-27c64d3b1e8a.mp4

**Comment by plankatron** [comment]
this is primarily done , closing issue
