### ISSUE TITLE
Refactor avatar animation/rendering

### ISSUE THREAD

**Issue by 0reo** [webaverse/app#2456]
The avatar animation update loop is also managing state logic, which is complicating adding new animations, transitioning between animations, and using multi-state animations.  Will be separating this logic into classes/state machine which the avatar class will then communicate with.  This should make adding new animations and transitions more straight forward and accessible to other developers

- [x] transition animation logic outside of of avatars.js https://github.com/webaverse/app/issues/2519
- [ ] make reasonable classes for defining animation logic https://github.com/webaverse/app/issues/2533
- [ ] create mechanim like state system for animations https://github.com/webaverse/app/issues/2532
