### ISSUE TITLE
Infinite Open World Generation

### ISSUE THREAD

**Issue by aryasalehi** [webaverse/app#2758]
### Goal
Procedural World generation with rivers, tunnels, mountains, villages, overhangs, plants, trees, streets and etc..
### Todo
- [ ] Procedurally generating geometry with the marching cubes technique
- [ ] Procedural shading for the terrain
- [ ] Creating assets to place on top of the terrain
- [ ] Uploading the assets source geometries to wasm, and then gluing them together to make a full chunk
### Useful links
- [Basic terrain generation technique](https://www.youtube.com/watch?v=hHGshzIXFWY&list=PLRL3Z3lpLmH3PNGZuDNf2WXnLTHpN9hXy)
### Visual References
- Fortnite 
- Minecraft
- [Terrain Editing](https://twitter.com/anastasiaopara/status/1510184072148041734?s=21&t=SF9MNO7D_7vppd_EM1MhVg) 
- [Minecraft terrain generator](https://www.youtube.com/watch?v=mIh0XKh2mPk&t=165s&ab_channel=AsianHalfSquat)
