### ISSUE TITLE
Dual Contouring : Generate Terrain With Sharp Features

### ISSUE THREAD

**Issue by aryasalehi** [webaverse/app#2826]
### Goal
generating a terrain with sharp features with Dual Contouring
### Todo
- [x] Implementing Octree
- [x] Placing a vertex in each voxel in the right position
- [x] solving the QEF
- [x] Implementing dual contouring algo : https://github.com/webaverse/app-wasm/pull/43
- [x] creating seams for the chunks : https://github.com/webaverse/app-wasm/pull/46
- [x] adding LOD for each chunk and getting clean seems between different LODs : https://github.com/webaverse/app-wasm/pull/50
- [x] adding biomes generation
- [x] coding the ubershader logic ( to have different shaders for each biomes )
- [x] using cached noise for the terrain to speed up the generation : https://github.com/webaverse/app-wasm/pull/58 
- [ ] generating the biomes weights based on geometric distance( WIP )
- [ ] creating a PR for biomes
- [ ] https://github.com/webaverse/app/issues/2761#issue-1193242234
- [ ] adjusting temp and humidity noises
- [ ] creating a LOD planner which walks an octree to generate the settings for our set of lods
- [ ] making the geometry generation asynchronous (worker capable and geometry streamed)
- [ ] tracking the player
- [ ] Optimizing ( parallelize, optimize copies and gc, cache )
### Useful Links
- [Implementing Dual Contouring](http://ngildea.blogspot.com/2014/11/implementing-dual-contouring.html)
- [Interactive Explanation](https://wordsandbuttons.online/interactive_explanation_of_marching_cubes_and_dual_contouring.html)
- [Tutorial](https://www.boristhebrave.com/2018/04/15/dual-contouring-tutorial/)
- [C++ Implementation](https://github.com/nickgildea/DualContouringSample)
