### ISSUE TITLE
Generating a simple chunk of terrain with height map

### ISSUE THREAD

**Issue by aryasalehi** [webaverse/app#2843]
### Description
this is a test task for Andrew
### Goal
generate a chunk of terrain in C++ and then render that in the app ( a simple height map )
bonus : ( generating a texture based on the heightmap in a shader with GLSL )
### Todo
- [ ] Generating the terrain map geometry inside C++
- [ ] Writing that to an output buffer
- [ ] Reading the output buffer inside JS
- [ ] Constructing the mesh in three.js
- [ ] Bonus : Using a ShaderMaterial to texture the mesh based on the heightmap
